#!/bin/bash
# `devcontainer features test` default scenario — runs INSIDE a container built from this
# Feature with **no options** (`"podman-as-docker": {}`) and **no consumer runArgs**.
#
# Since 0.2.0 this Feature grants no capability, and rootless podman inside the container
# works only when the consumer's runArgs carry a seccomp profile (see the README). The
# autogenerated default scenario has no runArgs at all, so a `docker run` cannot succeed here
# and is not attempted: this file checks everything the *build* is responsible for. The
# runtime claims — `docker run` with private networking, build, name DNS, the API socket —
# live in the scenarios (test/scenarios.json), whose runArgs carry the profile the way a
# consumer's would; `zero_caps` is the one that also asserts the bounding set.
#
# Unlike every other Feature in this collection, this one CANNOT tolerate the test
# command's own default base image — `ubuntu:focal` (20.04) does not carry a `podman`
# package at all (it predates Ubuntu's own packaging of it), so `install.sh` fails the
# build there, correctly (a failed install fails the build, same as every other Feature
# here). Run this scenario with an explicit, podman-carrying base image:
#
#   bash features/podman-as-docker/test/run-features-test.sh \
#     --base-image mcr.microsoft.com/devcontainers/base:ubuntu-24.04
set -e

source dev-container-features-test-lib

SHARE=/usr/local/share/devc-features/podman-as-docker
SOCK_DIR=/run/devc-features/podman-as-docker
GRAPHROOT=/var/lib/devc-features/podman-as-docker/storage

check "create-time script is installed" test -f "$SHARE/post-create.sh"
check "start-time script is installed" test -f "$SHARE/post-start.sh"
check "both are owned by uid 0 (by uid: with rootless-remap the name for uid 0 is the remote user's)" bash -c \
  "[ \"\$(stat -c '%u:%g' $SHARE/post-create.sh)\" = '0:0' ] &&
   [ \"\$(stat -c '%u:%g' $SHARE/post-start.sh)\" = '0:0' ]"

check "docker is on PATH" bash -c "command -v docker"
check "docker --version names podman, not a real Docker Engine" bash -c \
  "docker --version | grep -qi podman"
check "the podman-docker emulation banner is silenced on stderr" bash -c \
  "[ -z \"\$(docker --version 2>&1 >/dev/null)\" ]"
check "/etc/containers/nodocker exists (silenceEmulationNotice defaults true)" \
  test -e /etc/containers/nodocker

check "subuid has a range for the remote user" bash -c \
  "grep -q \"^\$(id -un):\" /etc/subuid"
check "subgid has a range for the remote user" bash -c \
  "grep -q \"^\$(id -un):\" /etc/subgid"

check "registries.conf.d resolves docker.io unqualified" test -f \
  /etc/containers/registries.conf.d/99-devc-podman-as-docker.conf
check "containers.conf.d defaults netns to host" grep -qxF 'netns = "host"' \
  /etc/containers/containers.conf.d/99-devc-podman-as-docker.conf

check "the graphroot volume is mounted (this Feature's own declared mount)" bash -c \
  "findmnt --target $GRAPHROOT >/dev/null 2>&1 || mountpoint -q $GRAPHROOT"
check "and owned by the remote user (the create-time ownership repair)" bash -c \
  "[ \"\$(stat -c '%U' $GRAPHROOT)\" = \"\$(id -un)\" ]"

check "storage.conf was written at create time" test -f "$HOME/.config/containers/storage.conf"
check "and chose overlay — the graphroot is a real filesystem, not the container's own" \
  grep -qxF 'driver = "overlay"' "$HOME/.config/containers/storage.conf"

# --- what 0.2.0 puts in the image instead of a capability ----------------------------------
check "newuidmap has cap_setuid as a file capability and no setuid bit" bash -c \
  "getcap /usr/bin/newuidmap | grep -q cap_setuid && [ ! -u /usr/bin/newuidmap ]"
check "newgidmap has cap_setgid" bash -c "getcap /usr/bin/newgidmap | grep -q cap_setgid"
check "the podman and docker shims are on PATH ahead of /usr/bin" bash -c \
  "[ \"\$(command -v podman)\" = /usr/local/bin/podman ] && [ \"\$(command -v docker)\" = /usr/local/bin/docker ]"
check "netavark and aardvark-dns are installed (name DNS)" bash -c \
  "[ -x /usr/lib/podman/netavark ] && [ -x /usr/lib/podman/aardvark-dns ]"
check "iptables is installed (netavark's firewall driver)" bash -c "command -v iptables"
check "/var/lib/cni exists" test -d /var/lib/cni
check "DOCKER_HOST names the fixed socket" bash -c \
  "[ \"\$DOCKER_HOST\" = \"unix://$SOCK_DIR/podman.sock\" ]"
check "the start-time step ran and left its log (the service itself needs the seccomp profile)" \
  test -f "$SOCK_DIR/service.log"

reportResults
