#!/bin/bash
# Run this Feature's `devcontainer features test` scenarios (test.sh, plus anything in
# scenarios.json).
#
# Why a wrapper: `devcontainer features test` insists on a *collection* layout —
# `<project>/src/<id>/` and `<project>/test/<id>/` — while this repo keeps each Feature
# self-contained under `features/<id>/`, which is also what `devcontainer features publish`
# wants. Rather than split one Feature across two trees to satisfy one command, stage a
# throwaway copy in the layout it expects.
#
# Needs Docker and a network (a Feature may download things, and the scenarios pull images), so
# this is run deliberately, not from `deno task test`. It needs no host-side prerequisite: no
# Feature in this collection declares a mount, so there are no bind sources to exist.
set -euo pipefail

FEATURE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ID="$(basename "$FEATURE_DIR")"
CLI="${DEVCONTAINER_CLI:-devcontainer}"

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT
mkdir -p "$STAGE/src/$ID" "$STAGE/test/$ID"
# The whole Feature directory minus its tests, rather than a list of files to keep in step
# with the Feature — a Feature that ships scripts/ alongside install.sh would otherwise stage
# an incomplete copy and fail inside the container, far from the omission. This file is
# identical in every Feature; copy it as-is.
cp -R "$FEATURE_DIR"/. "$STAGE/src/$ID/"
rm -rf "$STAGE/src/$ID/test"
# And the whole test directory, for the same reason in the other direction: the command reads
# test.sh, an optional scenarios.json, one script per scenario and an optional per-scenario
# config folder, and staging only test.sh silently drops every scenario a Feature declares.
cp -R "$FEATURE_DIR/test"/. "$STAGE/test/$ID/"
rm -f "$STAGE/test/$ID/run-features-test.sh"

# `--base-image`/`-i` only reaches the autogenerated default scenario (test.sh) — every named
# scenario in scenarios.json pins its own "image" regardless. Left unset, the CLI's own default
# is ubuntu:focal (20.04), which lacks curl and trips installers that assume it. Default instead
# to the floating tag every named scenario in this collection already uses, unless the caller
# passed their own (e.g. the podman-as-docker/rootless-remap CI, which needs a specific image).
BASE_IMAGE_ARGS=()
_has_base_image=0
for _arg in "$@"; do
  case "$_arg" in
    --base-image | --base-image=* | -i) _has_base_image=1 ;;
  esac
done
if [ "$_has_base_image" -eq 0 ]; then
  BASE_IMAGE_ARGS=(--base-image mcr.microsoft.com/devcontainers/base:ubuntu)
fi

exec "$CLI" features test --project-folder "$STAGE" --features "$ID" \
  "${BASE_IMAGE_ARGS[@]}" "$@"
