#!/bin/bash
# Runs on your host, before the container is created.
#
# Its job is to create the files and directories that devcontainer.json's `mounts` bind into
# the container. Docker fails a bind mount whose source is missing rather than creating it,
# so they have to exist first.
#
# Runs again on every subsequent start, and is safe to re-run.
set -e

# Claude Code config seed. Whatever you put here — CLAUDE.md, settings.json, statusline.sh —
# is linked into ~/.claude in the container. Edits on your host take effect live.
mkdir -p "$HOME/.config/devc/.claude"

# Your personal shell customization. Every bashrc_*.sh here is sourced by every interactive
# shell in the container. Created empty; nothing writes into it for you.
mkdir -p "$HOME/.config/devc/shell"

# Your git identity, for the container.
#
# The container's ~/.gitconfig is wiped on every rebuild, so it has no idea who you are.
# Rather than bind your whole host ~/.gitconfig — which would drag in host paths, credential
# helpers and signing config that do not work in a container — copy just your name and email
# into a file of their own.
#
# `git config --file` does the writing rather than `echo`, so a value containing `#`, `;`,
# `"` or `\` is quoted the way git's own parser expects to read it back. The file is written
# even when you have no identity configured, so the mount source always exists.
identity="$HOME/.config/devc/gitconfig-identity"
printf '%s\n' "# Generated by devc initialize-command.sh — do not edit." > "$identity"
name="$(git config --get user.name || true)"
email="$(git config --get user.email || true)"
[ -n "$name" ] && git config --file "$identity" user.name "$name"
[ -n "$email" ] && git config --file "$identity" user.email "$email"

# A non-zero exit here aborts container creation, and the tests above leave a failing status
# when you have no git identity set. Having none is a warning, not a reason to fail the build.
exit 0
